#!/bin/sh

### BEGIN INIT INFO
# Provides:          aesdsocket
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: aesdsocket daemon
### END INIT INFO

DAEMON=/usr/bin/aesdsocket
DAEMON_OPTS="-d"
PIDFILE=/var/run/aesdsocket.pid

case "$1" in
  start)
    echo "Starting aesdsocket: "
    start-stop-daemon --start --quiet --background \
      --make-pidfile --pidfile "$PIDFILE" --exec "$DAEMON" -- $DAEMON_OPTS
    echo "Done"
    ;;
  stop)
    echo "Stopping aesdsocket: "
    start-stop-daemon --stop --quiet --pidfile "$PIDFILE"
    echo "Done"
    ;;
  restart)
    "$0" stop
    "$0" start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
    ;;
esac

exit 0

